// <auto-generated />
using System;
using AiRecipe.Content.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiRecipe.Content.Api.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20260826114656_UpdateSeedDataToSwedish")]
    partial class UpdateSeedDataToSwedish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7697),
                            Name = "Pasta",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7703),
                            Name = "Soppa",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7704),
                            Name = "Sallad",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7705),
                            Name = "Gryta",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7706),
                            Name = "Asiatiskt",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllergen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7815),
                            IsAllergen = true,
                            Name = "Spaghetti",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 2,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7816),
                            IsAllergen = false,
                            Name = "Tomatsås",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 3,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7818),
                            IsAllergen = false,
                            Name = "Kycklingfilé",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 4,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7819),
                            IsAllergen = true,
                            Name = "Vispgrädde",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 5,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7820),
                            IsAllergen = true,
                            Name = "Lax",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 6,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7821),
                            IsAllergen = false,
                            Name = "Ris",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 7,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7822),
                            IsAllergen = false,
                            Name = "Linser",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 8,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7823),
                            IsAllergen = false,
                            Name = "Avokado",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FKCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portions")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecipeId");

                    b.HasIndex("FKCategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7857),
                            FKCategoryId = 1,
                            Instructions = "Koka pastan, blanda med varm sås.",
                            Portions = 4,
                            Title = "Snabb tomatpasta",
                            TotalTimeMinutes = 15,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = 2,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7860),
                            FKCategoryId = 2,
                            Instructions = "Stek kycklingen, tillsätt grädde och sjud.",
                            Portions = 2,
                            Title = "Krämig kycklingsoppa",
                            TotalTimeMinutes = 30,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = 3,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7862),
                            FKCategoryId = 3,
                            Instructions = "Grilla laxen och blanda med sallad och avokado.",
                            Portions = 2,
                            Title = "Laxsallad med avokado",
                            TotalTimeMinutes = 20,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = 4,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7863),
                            FKCategoryId = 4,
                            Instructions = "Koka linserna tills de är mjuka i en kryddig buljong.",
                            Portions = 6,
                            Title = "Linsgryta",
                            TotalTimeMinutes = 45,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = 5,
                            CreatedAt = new DateTime(2026, 8, 26, 11, 46, 56, 631, DateTimeKind.Utc).AddTicks(7865),
                            FKCategoryId = 5,
                            Instructions = "Stek kycklingen, servera med kokt ris.",
                            Portions = 3,
                            Title = "Kyckling med ris",
                            TotalTimeMinutes = 25,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("FKRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("FKIngredientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FKRecipeId", "FKIngredientId");

                    b.HasIndex("FKIngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            FKRecipeId = 1,
                            FKIngredientId = 1,
                            Amount = 400m,
                            Unit = "g"
                        },
                        new
                        {
                            FKRecipeId = 1,
                            FKIngredientId = 2,
                            Amount = 500m,
                            Unit = "g"
                        },
                        new
                        {
                            FKRecipeId = 2,
                            FKIngredientId = 3,
                            Amount = 300m,
                            Unit = "g"
                        },
                        new
                        {
                            FKRecipeId = 2,
                            FKIngredientId = 4,
                            Amount = 2m,
                            Unit = "dl"
                        },
                        new
                        {
                            FKRecipeId = 3,
                            FKIngredientId = 5,
                            Amount = 2m,
                            Unit = "st"
                        },
                        new
                        {
                            FKRecipeId = 3,
                            FKIngredientId = 8,
                            Amount = 1m,
                            Unit = "st"
                        },
                        new
                        {
                            FKRecipeId = 4,
                            FKIngredientId = 7,
                            Amount = 3m,
                            Unit = "dl"
                        },
                        new
                        {
                            FKRecipeId = 5,
                            FKIngredientId = 3,
                            Amount = 400m,
                            Unit = "g"
                        },
                        new
                        {
                            FKRecipeId = 5,
                            FKIngredientId = 6,
                            Amount = 4m,
                            Unit = "portioner"
                        });
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Recipe", b =>
                {
                    b.HasOne("AiRecipe.Content.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("FKCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("AiRecipe.Content.Api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("FKIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiRecipe.Content.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("FKRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
