// <auto-generated />
using System;
using AiRecipe.Content.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiRecipe.Content.Api.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20260326133718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3854),
                            Name = "Pasta",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3857),
                            Name = "Soup",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3858),
                            Name = "Salad",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3858),
                            Name = "Stew",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3859),
                            Name = "Asian",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllergen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3956),
                            IsAllergen = true,
                            Name = "Spaghetti",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 2,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3957),
                            IsAllergen = false,
                            Name = "Tomato Sauce",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 3,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3958),
                            IsAllergen = false,
                            Name = "Chicken Breast",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 4,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3959),
                            IsAllergen = true,
                            Name = "Heavy Cream",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 5,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3960),
                            IsAllergen = true,
                            Name = "Salmon",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 6,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3961),
                            IsAllergen = false,
                            Name = "Rice",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 7,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3962),
                            IsAllergen = false,
                            Name = "Lentils",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IngredientId = 8,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3963),
                            IsAllergen = false,
                            Name = "Avocado",
                            Type = "",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FKCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portions")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecipeId");

                    b.HasIndex("FKCategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(3998),
                            FKCategoryId = 1,
                            Instructions = "Boil pasta, mix with warm sauce.",
                            Portions = 4,
                            Title = "Quick Tomato Pasta",
                            TotalTimeMinutes = 15,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = 2,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(4000),
                            FKCategoryId = 2,
                            Instructions = "Sauté chicken, add cream and simmer.",
                            Portions = 2,
                            Title = "Creamy Chicken Soup",
                            TotalTimeMinutes = 30,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = 3,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(4002),
                            FKCategoryId = 3,
                            Instructions = "Grill the salmon and mix with salad and avocado.",
                            Portions = 2,
                            Title = "Salmon Salad with Avocado",
                            TotalTimeMinutes = 20,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = 4,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(4003),
                            FKCategoryId = 4,
                            Instructions = "Cook lentils until soft in a spicy broth.",
                            Portions = 6,
                            Title = "Lentil Stew",
                            TotalTimeMinutes = 45,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = 5,
                            CreatedAt = new DateTime(2026, 3, 26, 13, 37, 18, 75, DateTimeKind.Utc).AddTicks(4004),
                            FKCategoryId = 5,
                            Instructions = "Fry the chicken, serve with boiled rice.",
                            Portions = 3,
                            Title = "Chicken with Rice",
                            TotalTimeMinutes = 25,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("FKRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("FKIngredientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FKRecipeId", "FKIngredientId");

                    b.HasIndex("FKIngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            FKRecipeId = 1,
                            FKIngredientId = 1,
                            Amount = 400m,
                            Unit = "g"
                        },
                        new
                        {
                            FKRecipeId = 1,
                            FKIngredientId = 2,
                            Amount = 500m,
                            Unit = "g"
                        },
                        new
                        {
                            FKRecipeId = 2,
                            FKIngredientId = 3,
                            Amount = 300m,
                            Unit = "g"
                        },
                        new
                        {
                            FKRecipeId = 2,
                            FKIngredientId = 4,
                            Amount = 2m,
                            Unit = "dl"
                        },
                        new
                        {
                            FKRecipeId = 3,
                            FKIngredientId = 5,
                            Amount = 2m,
                            Unit = "pcs"
                        },
                        new
                        {
                            FKRecipeId = 3,
                            FKIngredientId = 8,
                            Amount = 1m,
                            Unit = "pcs"
                        },
                        new
                        {
                            FKRecipeId = 4,
                            FKIngredientId = 7,
                            Amount = 3m,
                            Unit = "dl"
                        },
                        new
                        {
                            FKRecipeId = 5,
                            FKIngredientId = 3,
                            Amount = 400m,
                            Unit = "g"
                        },
                        new
                        {
                            FKRecipeId = 5,
                            FKIngredientId = 6,
                            Amount = 4m,
                            Unit = "servings"
                        });
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Recipe", b =>
                {
                    b.HasOne("AiRecipe.Content.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("FKCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("AiRecipe.Content.Api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("FKIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiRecipe.Content.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("FKRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("AiRecipe.Content.Api.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
